const mongoose=require("mongoose");
const menuItemSchema=new mongoose.Schema(
  {
    vendor:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"User",
      required:true
    },
    name:{
      type:String,
      required:true,
    },
    description:String,
    price:{
      type:Number,
      required:true
    },
    image:String,
    category:{
      type:String,
      ref:"Category",
      required:true
    },
    isAvailable:{
      type:Boolean,
      default:true
    },
    restaurant:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"Restaurant",
      required:true,
    }
  },
  {timestamp:true}
);
module.exports=mongoose.model("MenuItem",menuItemSchema);