const mongoose=require("mongoose");
const orderSchema=new mongoose.Schema(
  {
    user:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"User",
      required:true
    },
    vendor:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"User",
      required:true
    },
    items:[
      {
        menuItem:{
          type:mongoose.Schema.Types.ObjectId,
          ref:"MenuItem"
        },
        name:String,
        price:Number,
        quantity:Number
      }
    ],
    totalAmount:{
      type:Number,
      require:true
    },
    address:Object,
    status:{
      type:String,
      enum:[
        "pending",
        "accepted",
        "preparing",
        "out_for_delivery",
        "delivered",
        "cancelled"
      ],
      default:"pending"
    },
    prepTime:{
      type:Number,
      default:0
    },
    paymentStatus:{
      type:String,
      enum:["pending","paid"],
      default:"pending"
    },
    paymentMethod:{
      type:String,
      enum:["cod","online"]
    }
  },
  {timestamps:true}
);
module.exports=mongoose.model("Order",orderSchema);